server:
  port: 8021

spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    publisher-confirm-type: correlated   #确认消息已发送到交换机(Exchange)
    publisher-returns: true    #确认消息已发送到队列(Queue)