GET http://localhost:8891/login?token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2tlciIsInJvbGUiOiJieHNoZW5nIiwiaXNzIjoiZWNoaXNhbiIsImV4cCI6MTYyNDk0NTkyMSwiaWF0IjoxNjI0OTM1MTIxfQ.EH_c4hLQ_qOfnOY1rELHCcwV42UTh-uyjYnr1Hz7YZhiggzOs4Gd8BUCLuFfEaO7_tmKPTsLi3G6sj0PmEHcJQ

