server:
  port: 5000

spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true #覆盖之前相同名称的bean
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848/

