server:
  port: 8082 #服务器端口

spring:
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 0
    # password:
    pool:
      # 连接池中的最小空闲连接
      minIdle: 1
      # 连接池中的最大空闲连接
      maxIdle: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      maxWait: 3
      # 连接池最大连接数（使用负值表示没有限制）
      maxActive: 8
